
server:
  port: 8761  #eureka ??? ? ??? ???? ????? ??? ??? ????  #???? ????

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false   # ? ? ???? ??? ??? true? ??? ?? ??? ??? ???? ?
    fetch-registry: false         # ?????? eureka ??? ?? ???? ???